// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF4G2m-NbhmP76Tpb5ZqjXm-qd2afX0Oc',
    appId: '1:712968065144:web:8ea0d88eb161fbb3e11d8d',
    messagingSenderId: '712968065144',
    projectId: 'login-f2489',
    authDomain: 'login-f2489.firebaseapp.com',
    storageBucket: 'login-f2489.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO6VszOoeElQcgDnqOq_-SYJ2r3vfG5Mg',
    appId: '1:712968065144:android:ee7a2a7bd37c22e2e11d8d',
    messagingSenderId: '712968065144',
    projectId: 'login-f2489',
    storageBucket: 'login-f2489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNfHoenEjgHTj7u7XOYE5MPWecNO1Js4',
    appId: '1:712968065144:ios:dc624b1902b39530e11d8d',
    messagingSenderId: '712968065144',
    projectId: 'login-f2489',
    storageBucket: 'login-f2489.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNfHoenEjgHTj7u7XOYE5MPWecNO1Js4',
    appId: '1:712968065144:ios:28a39cc212159060e11d8d',
    messagingSenderId: '712968065144',
    projectId: 'login-f2489',
    storageBucket: 'login-f2489.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
